name: flutterhackthema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Dependencies (alphabetically sorted)
  async: ^2.11.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.2.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  logger: ^2.6.2
  riverpod_annotation: ^3.0.3
  uuid: ^4.5.2

dev_dependencies:
  # Flutter SDK
  flutter_test:
    sdk: flutter

  # Dev dependencies (alphabetically sorted)
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  go_router_builder: ^4.1.0
  json_serializable: ^6.11.1
  mockito: ^5.5.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
